// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYpWbcvtFGUh2wZafX-HyxvYlT4AsOao4',
    appId: '1:317595955878:web:b345362abd715d5c137a67',
    messagingSenderId: '317595955878',
    projectId: 'fir-india-b9178',
    authDomain: 'fir-india-b9178.firebaseapp.com',
    storageBucket: 'fir-india-b9178.firebasestorage.app',
    measurementId: 'G-D1KX3EXWMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxuuYaRRNpi0PV2U1Lus8bacnexOACOyE',
    appId: '1:317595955878:android:c8cbbc6dfc5a17bc137a67',
    messagingSenderId: '317595955878',
    projectId: 'fir-india-b9178',
    storageBucket: 'fir-india-b9178.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ukE3C8OYWHBK_2kZCCoK-XVbrnh_JKA',
    appId: '1:317595955878:ios:ba84c3714563c41f137a67',
    messagingSenderId: '317595955878',
    projectId: 'fir-india-b9178',
    storageBucket: 'fir-india-b9178.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIndia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ukE3C8OYWHBK_2kZCCoK-XVbrnh_JKA',
    appId: '1:317595955878:ios:ba84c3714563c41f137a67',
    messagingSenderId: '317595955878',
    projectId: 'fir-india-b9178',
    storageBucket: 'fir-india-b9178.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIndia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYpWbcvtFGUh2wZafX-HyxvYlT4AsOao4',
    appId: '1:317595955878:web:1ebeaf55f8065a71137a67',
    messagingSenderId: '317595955878',
    projectId: 'fir-india-b9178',
    authDomain: 'fir-india-b9178.firebaseapp.com',
    storageBucket: 'fir-india-b9178.firebasestorage.app',
    measurementId: 'G-2VZT2Q3DEZ',
  );
}
